CREATE TABLE Workout(
   Name          VARCHAR(48) NOT NULL PRIMARY KEY
  ,ID            VARCHAR(21)
  ,PrimaryMuscle VARCHAR(22) NOT NULL
);
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Flat Dumbbell Bench Press','2','1');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Incline Barbell Bench Press','3','1');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Incline Dumbbell Bench Press','4','1');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Decline Barbell Bench Press','5','1');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Decline Dumbbell Bench Press','6','1');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Flat Chest Press Machine','7','1');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Flat Barbell Bench Press','1','1');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Incline Chest Press Machine','8','1');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Decline Chest Press Machine','9','1');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Dips (on parallel bars with slight forward lean)','10','1');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Push-Ups','11','1');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Flat Dumbbell Flyes','12','1');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Incline Dumbbell Flyes','13','1');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Decline Dumbbell Flyes','14','1');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Pec Deck Machine','15','1');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Cable Crossovers/Cable Flyes','16','1');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Pull-Ups','17','2');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Chin-Ups','18','2');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Lat Pull-Downs','19','2');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Bent Over Barbell Rows','20','2');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Dumbbell Rows','21','2');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('T-Bar Rows','22','2');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Seated Cable Rows','23','2');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Chest Supported Barbell','24','2');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Chest Supported Dumbbell Rows','25','2');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Chest Supported Machine Rows','26','2');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Inverted Rows','27','2');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Barbell Shrugs','28','11');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Machine Shrugs','29','11');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Dumbbell Shrugs','30','11');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Seated Overhead Barbell','31','5');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Seated Overhead Dumbbell Press','32','5');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Standing Overhead Barbell Press','33','5');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Standing Overhead Dumbbell Press','34','5');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Overhead Machine Press','35','5');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Arnold Press','36','5');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Barbell Upright Row','37','5');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Dumbbell Upright Row','38','5');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Machine Upright Rows','39','5');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Dumbbell Lateral Raise','40','5');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Machine Lateral Raise',NULL,'41',5,NULL);
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Cable Lateral Raise','42','5');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Dumbbell Front Raises','43','5');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Cable Front Raises','44','5');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Machine Front Raises','45','5');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Barbell Rear Delt Rows','46','5');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Dumbbell Rear Delt Rows','47','5');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Machine Rear Delt Rows','48','5');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Barbell Rear Delt Flies','49','5');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Dumbbell Rear Delt Flies','50','5');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Machine Rear Delt Flies','51','5');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Barbell Squats','52','6');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Barbell Front Squats','53','6');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Barbell Split Squats','54','6');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Barbell Lunges','55','6');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Barbell Step-Ups','56','6');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Leg Press','57','6');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Machine Squat/Hack Squat','58','6');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Leg Extensions','59','6');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Barbell Romanian Deadlifts','60','7');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Barbell Straight Leg Deadlifts','61','7');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Barbell Sumo Deadlifts','62','7');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Glute-Ham Raises','62','7');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Hyperextensions','63','7');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Cable Pull-Throughs','64','7');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Good-Mornings','65','7');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Leg Curls','66','7');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Standing Barbell Curls','67','3');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Standing Dumbbell Curls','68','3');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Barbell Preacher Curls','69','3');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Dumbbell Preacher Curls','70','3');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Seated Dumbbell Curls','71','3');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Incline Dumbbell Curls','72','3');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Hammer Curls','73','3');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Concentration Curls','74','3');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Cable Curls','75','3');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Dips (on parallel bars','elbows close to body','without forward lean)',76,4);
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Flat Close Grip Bench Press','77','4');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Decline Close Grip Bench Press','78','4');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Close Grip Push-Ups','79','4');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Laying Barbell Tricep Extensions','80','4');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Laying Dumbbell Tricep Extensions','81','4');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Skull Crushers','82','4');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Overhead Barbell Tricep Extensions','83','4');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Overhead Dumbbell Tricep Extensions','84','4');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Cable Press-Downs','85','4');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Bench Dips','86','4');
INSERT INTO Workout(Name,ID,PrimaryMuscle) VALUES ('Biceps Curl Machine','87','3');
